FROM nginx:stable-alpine-slim

COPY nginx.conf /etc/nginx/nginx.conf

RUN chown -R nginx:nginx /var/cache/nginx /var/run

USER nginx
EXPOSE 8080

# docker build -f docker/Dockerfile.nginx -t sscms/nginx docker
