volumes:

  volume-mysql:
    driver: local

  volume-sscms:
    driver: local

services:

  sscms-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${SSCMS_MYSQL_ROOT_PASSWORD:?set SSCMS_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: sscms
      MYSQL_USER: sscms
      MYSQL_PASSWORD: ${SSCMS_DATABASE_PASSWORD:?set SSCMS_DATABASE_PASSWORD}
    volumes:
      - volume-mysql:/var/lib/mysql

  sscms-core:
    depends_on:
      - sscms-mysql
    image: "sscms/core"
    restart: always
    ports:
      - "80:8080"
    environment:
      SSCMS_SECURITY_KEY: ${SSCMS_SECURITY_KEY:?set SSCMS_SECURITY_KEY}
      SSCMS_DATABASE_TYPE: MySQL
      SSCMS_DATABASE_HOST: sscms-mysql
      SSCMS_DATABASE_USER: sscms
      SSCMS_DATABASE_PASSWORD: ${SSCMS_DATABASE_PASSWORD:?set SSCMS_DATABASE_PASSWORD}
      SSCMS_DATABASE_NAME: sscms
    volumes:
      - volume-sscms:/app/wwwroot

# docker-compose up -d
# docker-compose down

# Browse to: http://localhost/ss-admin/
